### ISSUE TITLE
Digital Signature

### ISSUE THREAD

**Issue by TyMac** [last-byte/PersistenceSniper#3]
In regulated environments it may be difficult to run the script given it's not digitally signed. Would be great if you added that as a feature. Thanks!

**Comment by RiccardoAncarani** [comment]
Hi,

Thanks for the feedback. I think that in order to do that we would need to acquire a code signing certificate that would cost us money. The best option I can think of is that if you have an internal PKI system it would be easier to sign it with a certificate issued by that.

**Comment by last-byte** [comment]
Hi @TyMac, 
I'm currently working on deploying a signing action with Github actions and a valid Code Signing Certificate (not EV, I'm too cheap). It should be up and running within a couple of days.

Cheers.

**Comment by TyMac** [comment]
That's awesome!!!

**Comment by last-byte** [comment]
Hi, as requested this has been implemented with commit [5b5dbbd](https://github.com/last-byte/PersistenceSniper/commit/5b5dbbd5e8aec09f9d91bfb0eed03a23c61a055b)

**Comment by RiccardoAncarani** [comment]
Hi,

Thanks for the feedback. I think that in order to do that we would need to
acquire a code signing certificate that would cost us money. The best
option I can think of is that if you have an internal PKI system it would
be easier to sign it with a certificate issued by that.

Il giorno dom 7 ago 2022 alle 04:30 TyMac ***@***.***> ha
scritto:
